engines:
  duplication:
    enabled: true
  eslint:
    enabled: true
  scss-lint:
    enabled: true
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
  - web/**
  - protected/**
exclude_paths:
- web/css/material/**
- web/js/Leaflet.Control.Geocoder/**
- web/js/material/**
- web/js/selectize.js-0.11.2/**
- web/pdfjs/**
- docs/**
- tests/** # TODO Nur automatisch generierte Dateien ausschließen
