---
engines:
  scss-lint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "codesize,design,unusedcode,docs/phpmd-ruleset.xml"
checks:
  method-complexity:
    enabled: false
  method-lines:
    config:
      threshold: 30
ratings:
  paths:
  - "html/css/*.scss"
  - "protected/**.php"

exclude_paths:
- config/
- node_modules/
- tests/
- vendor/
- html/bower/
- html/css/build/
- html/pdfjs/
- html/js/Leaflet.Control.Geocoder
- html/css/_material.scss
- html/css/material
- html/css/_shariff.scss
