---
engines:
  scss-lint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "cleancode,codesize,design,naming,unusedcode"

ratings:
  paths:
  - "html/css/*.scss"
  - "protected/**.php"

exclude_paths:
- config/
- node_modules/
- tests/
- vendor/
- html/bower/
- html/css/build/
