language: php
sudo: false

php:
  - '5.6'
#  - '7.0'
#  - hhvm

cache:
  directories:
    - node_modules
    - html/bower
    - vendor
    - $HOME/.composer/cache

services:
  - mysql

addons:
  apt:
    packages:
      - nginx

install:
#  - cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - composer install
  - npm install
  - npm install bower
  - node_modules/bower/bin/bower install 
  - gulp
  - mysql -e 'create database ris;'

before_script:
  - nginx -c `pwd`/docs/nginx-travis.conf
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm

script:
  - vendor/bin/codecept run


after_script:
  - nginx -c `pwd`/docs/nginx-travis.conf -s stop
  - docs/require-clean-working-tree.sh # git shouldn't recognize any altered files after installing the dependencies and running the tests
