language: php
sudo: false

php:
  - '5.6'
#  - '7.0'
#  - hhvm

# Note: For using PHP 7 you have add the following line:
# cp /home/travis/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default /home/travis/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf

cache:
  apt: true
  directories:
    - node_modules
    - html/bower
    - vendor
    - $HOME/.composer/cache

services:
  - mysql

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - nginx
      - openjdk-8-jre

install:
  # Create environment for the webserver running in travis ci
  - cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - phpenv config-rm xdebug.ini # Speeds up build
  - phpenv config-add docs/travis.php.ini
  - ln -s `pwd` /tmp/muenchen-transparent
  - java -version
  
  # Create yii-environment
  - mkdir protected/runtime
  - mkdir html/assets

  # Set up mysql
  - mysql -e 'create database ristest;'
  - mysql -uroot --execute="SET GLOBAL time_zone = '+1:00'";
  - cat docs/schema.sql tests/_data/data.sql >  tests/_data/dump.sql
  - mysql -utravis ristest < tests/_data/dump.sql

  # Install dependencies
  - chmod 644 vendor/heise/shariff/index.php || true # Prevent a weird "has uncommitted changes" error message when updating shariff
  - composer install --prefer-source # --prefer-source fixes github's limits
  - npm install
  - npm install bower
  - node_modules/bower/bin/bower install
  - gulp

script:
  - nginx -c `pwd`/docs/nginx-codeception.conf
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - vendor/bin/codecept run

after_failure:
  - vendor/bin/codecept run --debug
  - cat protected/runtime/application.log
  - cat /tmp/error.log
  - cat /tmp/access.log
  - cat ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - cat tests/_output/*.html
  - find /home/travis/.phpenv/ -printf "%TY-%Tm-%Td\t%s\t%p\n"

after_script:
  - nginx -c `pwd`/docs/nginx-codeception.conf -s stop
  - docs/require-clean-working-tree.sh # git shouldn't recognize any altered files after installing the dependencies and running the tests
