nginx:
  image: nginx:1.11
  volumes:
   - ./docs/docker/nginx/muctransparent.conf:/etc/nginx/conf.d/muctransparent.conf
   - .:/var/www/ris3
  ports:
   - "8080:80"
  links:
    - php
    - solr
  command: /bin/bash -c "mkdir -p /var/www/ris3-data && (rm /etc/nginx/conf.d/default.conf || true) && nginx -g 'daemon off;'"

php:
  build: .
  ports:
    - "9000:9000"
  volumes:
    - .:/var/www/ris3
  links:
    - database
    - solr

database:
  image: mariadb:10.1
  volumes:
    - ./docs/schema.sql:/docker-entrypoint-initdb.d/00-schema.sql
    - ./docs/beispieldaten.sql:/docker-entrypoint-initdb.d/01-data.sql
    - ./docs/triggers.sql:/docker-entrypoint-initdb.d/02-triggers.sql
  command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  environment:
    MYSQL_ROOT_PASSWORD: muctransparent
    MYSQL_DATABASE: muctransparent
    MYSQL_USER: ris
    MYSQL_PASSWORD: sec
  ports:
    - "3306:3306"

solr:
  image: solr:5.5.1
  volumes:
    - ./docs/solr-core:/opt/solr/server/solr/muenchen-transparent
  ports:
    - "8983:8983"
